repos:
  # Black: formateador automático de código
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Reemplázalo con la última versión
    hooks:
      - id: black

  # Flake8: herramienta de linting para Python
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Reemplázalo con la última versión
    hooks:
      - id: flake8
        args: [--max-line-length=88]  # Configuración personalizada opcional

  # isort: organiza automáticamente las importaciones
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black]

  # Pre-commit-hooks: colección de hooks generales
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml  # Verifica la sintaxis YAML
      - id: end-of-file-fixer  # Asegura una línea en blanco al final de los archivos
      - id: trailing-whitespace  # Elimina espacios en blanco al final de las líneas

  # MyPy: chequeo de tipos estáticos
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]

  # Jupytext: sincroniza notebooks y Markdown
  - repo: https://github.com/mwouts/jupytext
    rev: v1.14.6
    hooks:
      - id: jupytext
        args: ["--sync"]
        exclude: "^book/_build/"
